spring:
    batch:
        job:
            enabled: false
    hadoop:
        fsUri: hdfs://node1:8020
        resourceManagerHost: node1
    yarn:
        batch:
            enabled: true
            name: job
            jobs:
              - name: job
                enabled: true
                next: true
                parameters:
                  ? inputPatterns
                  : "/syarn-tmp/batch-files/set1/*"
        appName: test-batch-files
        applicationDir: /app/test-batch-files/
        client:
            files:
              - "file:test-batch-files/build/libs/test-batch-files-container-2.0.0.BUILD-SNAPSHOT.jar"
              - "file:test-batch-files/build/libs/test-batch-files-appmaster-2.0.0.BUILD-SNAPSHOT.jar"
            launchcontext:
                archiveFile: test-batch-files-appmaster-2.0.0.BUILD-SNAPSHOT.jar
                includeSystemEnv: false
        appmaster:
            keepContextAlive: false
            launchcontext:
                archiveFile: test-batch-files-container-2.0.0.BUILD-SNAPSHOT.jar
