spring:
    yarn:
        appName: activator-boot
        applicationDir: /app/activator-sample/
        fsUri: hdfs://localhost:8020
        rmAddress: localhost:8032
        schedulerAddress: localhost:8030
        client:
            memory: 500
            virtualCores: 2
            appmasterFile: activator-boot-appmaster-2.0.0.BUILD-SNAPSHOT.jar
            files:
              - "file:activator-boot/build/libs/activator-boot-container-2.0.0.BUILD-SNAPSHOT.jar"
              - "file:activator-boot/build/libs/activator-boot-appmaster-2.0.0.BUILD-SNAPSHOT.jar"
        appmaster:
            memory: 500
            containerCount: 2
            appmasterClass: org.springframework.yarn.am.StaticEventingAppmaster
            containerFile: activator-boot-container-2.0.0.BUILD-SNAPSHOT.jar
