spring:
    hadoop:
        fsUri: hdfs://localhost:8020
        resourceManagerHost: localhost
    yarn:
        appName: test-activator-annotations
        applicationDir: /app/test-activator-annotations/
        client:
            files:
              - "file:test-activator/build/libs/test-activator-annotations-container-2.0.0.BUILD-SNAPSHOT.jar"
              - "file:test-activator/build/libs/test-activator-annotations-appmaster-2.0.0.BUILD-SNAPSHOT.jar"
            resource:
                memory: 500
                virtualCores: 2
            launchcontext:
                archiveFile: test-activator-annotations-appmaster-2.0.0.BUILD-SNAPSHOT.jar
        appmaster:
            containerCount: 2
            appmasterClass: org.springframework.yarn.am.StaticEventingAppmaster
            resource:
                memory: 500
            launchcontext:
                archiveFile: test-activator-annotations-container-2.0.0.BUILD-SNAPSHOT.jar
                arguments:
                  ? argumentsKeyFoo1
                  : argumentsValFoo1
