spring:
    yarn:
        appName: test-staging-default
        fsUri: hdfs://localhost:8020
        resourceManagerHost: localhost
        client:
            files:
              - "file:test-staging-default/build/libs/test-staging-default-container-2.0.0.BUILD-SNAPSHOT.jar"
              - "file:test-staging-default/build/libs/test-staging-default-appmaster-2.0.0.BUILD-SNAPSHOT.jar"
            launchcontext:
                archiveFile: test-staging-default-appmaster-2.0.0.BUILD-SNAPSHOT.jar
        appmaster:
            containerCount: 1
            launchcontext:
                archiveFile: test-staging-default-container-2.0.0.BUILD-SNAPSHOT.jar
