spring:
    hadoop:
        fsUri: hdfs://localhost:8020
        resourceManagerHost: localhost
    yarn:
        appName: test-multi-context
        applicationDir: /app/test-multi-context/
        client:
            files:
              - "file:test-multi-context/build/libs/test-multi-context-container-2.0.0.BUILD-SNAPSHOT.jar"
              - "file:test-multi-context/build/libs/test-multi-context-appmaster-2.0.0.BUILD-SNAPSHOT.jar"
            launchcontext:
                options:
                  - -Xms200m
                archiveFile: test-multi-context-appmaster-2.0.0.BUILD-SNAPSHOT.jar
        appmaster:
            containerCount: 2
            launchcontext:
                options:
                  - -Xms150m
                archiveFile: test-multi-context-container-2.0.0.BUILD-SNAPSHOT.jar
