spring:
    yarn:
        appName: test-staging-home
        stagingDir: inhome
        fsUri: hdfs://localhost:8020
        resourceManagerHost: localhost
        client:
            files:
              - "file:test-staging-home/build/libs/test-staging-home-container-2.0.0.BUILD-SNAPSHOT.jar"
              - "file:test-staging-home/build/libs/test-staging-home-appmaster-2.0.0.BUILD-SNAPSHOT.jar"
            launchcontext:
                archiveFile: test-staging-home-appmaster-2.0.0.BUILD-SNAPSHOT.jar
        appmaster:
            containerCount: 1
            launchcontext:
                archiveFile: test-staging-home-container-2.0.0.BUILD-SNAPSHOT.jar
