spring:
    hadoop:
        fsUri: hdfs://localhost:8020
        resourceManagerHost: localhost
    yarn:
        appName: test-container-launch-failure
        applicationDir: /app/test-container-launch-failure/
        client:
            files:
              - "file:test-activator/build/libs/test-container-launch-failure-container-2.0.0.BUILD-SNAPSHOT.jar"
              - "file:test-activator/build/libs/test-container-launch-failure-appmaster-2.0.0.BUILD-SNAPSHOT.jar"
            resource:
                memory: 500
            launchcontext:
                archiveFile: test-container-launch-failure-appmaster-2.0.0.BUILD-SNAPSHOT.jar
        appmaster:
            containerCount: 1
            appmasterClass: org.springframework.yarn.am.StaticEventingAppmaster
            resource:
                memory: 500
            launchcontext:
                archiveFile: notfound-test-container-launch-failure-container-2.0.0.BUILD-SNAPSHOT.jar
