spring:
    yarn:
        appName: multi-context
        applicationDir: /app/multi-context/
        fsUri: hdfs://localhost:8020
        rmAddress: localhost:8032
        schedulerAddress: localhost:8030
        client:
            options:
              - -Xms200m
            appmasterFile: multi-context-boot-appmaster-2.0.0.BUILD-SNAPSHOT.jar
            files:
              - "file:multi-context-boot/build/libs/multi-context-boot-container-2.0.0.BUILD-SNAPSHOT.jar"
              - "file:multi-context-boot/build/libs/multi-context-boot-appmaster-2.0.0.BUILD-SNAPSHOT.jar"
        appmaster:
            options:
              - -Xms150m
            containerCount: 2
            containerFile: multi-context-boot-container-2.0.0.BUILD-SNAPSHOT.jar
        container:
            xxxcontainerClazz: org.springframework.yarn.examples.MultiContextContainer

