spring:
    hadoop:
        fsUri: hdfs://localhost:8020
        resourceManagerHost: localhost
    yarn:
        appName: test-install-submit
        client:
            clientClass: org.springframework.yarn.client.DefaultApplicationYarnClient
            files:
              - "file:test-install-submit/build/libs/test-install-submit-container-2.0.0.BUILD-SNAPSHOT.jar"
              - "file:test-install-submit/build/libs/test-install-submit-appmaster-2.0.0.BUILD-SNAPSHOT.jar"
            resource:
                memory: 500
                virtualCores: 2
            launchcontext:
                archiveFile: test-install-submit-appmaster-2.0.0.BUILD-SNAPSHOT.jar
        appmaster:
            containerCount: 2
            appmasterClass: org.springframework.yarn.am.StaticEventingAppmaster
            resource:
                memory: 500
            launchcontext:
                archiveFile: test-install-submit-container-2.0.0.BUILD-SNAPSHOT.jar
