spring:
    hadoop:
        fsUri: hdfs://localhost:8020
        resourceManagerHost: localhost
    yarn:
        appName: test-staging-global
        stagingDir: /tmp/test-staging-global
        client:
            files:
              - "file:test-staging-global/build/libs/test-staging-global-container-2.0.0.BUILD-SNAPSHOT.jar"
              - "file:test-staging-global/build/libs/test-staging-global-appmaster-2.0.0.BUILD-SNAPSHOT.jar"
            launchcontext:
                archiveFile: test-staging-global-appmaster-2.0.0.BUILD-SNAPSHOT.jar
        appmaster:
            containerCount: 1
            launchcontext:
                archiveFile: test-staging-global-container-2.0.0.BUILD-SNAPSHOT.jar
