spring:
    hadoop:
        fsUri: hdfs://localhost:8020
        resourceManagerHost: localhost
    yarn:
        appName: test-multi-context-zip
        applicationDir: /app/test-multi-context-zip/
        client:
            files:
              - "file:test-multi-context-zip/build/libs/test-multi-context-zip-container-2.0.0.BUILD-SNAPSHOT.zip"
              - "file:test-multi-context-zip/build/libs/test-multi-context-zip-appmaster-2.0.0.BUILD-SNAPSHOT.zip"
            launchcontext:
                archiveFile: test-multi-context-zip-appmaster-2.0.0.BUILD-SNAPSHOT.zip
            localizer:
                patterns:
                  - "*.jar"
        appmaster:
            containerCount: 1
            launchcontext:
                archiveFile: test-multi-context-zip-container-2.0.0.BUILD-SNAPSHOT.zip
            localizer:
                patterns:
                  - "*.jar"
