spring:
    batch:
        job:
            enabled: false
    datasource:
        url: jdbc:mysql://localhost:3306/batch
        username: batch
        password: batch
        driverClassName: com.mysql.jdbc.Driver
    yarn:
        batch:
            enabled: true
            name: job
            jobs:
              - name: job
                enabled: true
                next: true
                failNext: false
                restart: true
                failRestart: false
                parameters:
                  ? job1key1
                  : job1val1
                  ? job1key2
                  : job1val2
        appName: batch-restart-db-boot
        applicationDir: /app/batch-restart-db-boot/
        fsUri: hdfs://localhost:8020
        rmAddress: localhost:8032
        schedulerAddress: localhost:8030
        client:
            appmasterFile: batch-restart-db-boot-appmaster-2.0.0.BUILD-SNAPSHOT.jar
            files:
              - "file:batch-restart-db-boot/build/libs/batch-restart-db-boot-container-2.0.0.BUILD-SNAPSHOT.jar"
              - "file:batch-restart-db-boot/build/libs/batch-restart-db-boot-appmaster-2.0.0.BUILD-SNAPSHOT.jar"
        appmaster:
            waitLatch: false
            containerCount: 2
            xxxappmasterClass: org.springframework.yarn.batch.am.BatchAppmaster
            containerFile: batch-restart-db-boot-container-2.0.0.BUILD-SNAPSHOT.jar
